### PR TITLE
Fix build for OS X / macOS

### PR DESCRIPTION
**Pull request by nils-eilers**

### CODE REVIEW

**Review by dfffffff — COMMENTED** [review]
What error do you get for the commit https://github.com/dfffffff/gcc6809/pull/2/commits/d24339b41879e32f43c49ec36ebf5ddaeab9c3b8 ?

**Comment by nils-eilers** [comment]
GCC's documentation says that compiling GCC with any other compiler than GCC isn't officially supported but the default compiler on OS X is clang these days, so I installed GCC 4.3.6 from Macports and used that to build GCC6809 on my Mac.

Here's the error log:

```
gcc   -DTARGET_GCC_VERSION=4003 -O2 -fomit-frame-pointer -DIN_GCC -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -pedantic -Wno-long-long -Wno-variadic-macros 				     -Wno-overlength-strings    -DHAVE_CONFIG_H  -o cc1plus-dummy \
	      cp/cp-lang.o stub-objc.o cp/call.o cp/decl.o cp/expr.o cp/pt.o cp/typeck2.o cp/class.o cp/decl2.o cp/error.o cp/lex.o cp/parser.o cp/ptree.o cp/rtti.o cp/typeck.o cp/cvt.o cp/except.o cp/friend.o cp/init.o cp/method.o cp/search.o cp/semantics.o cp/tree.o cp/repo.o cp/dump.o cp/optimize.o cp/mangle.o cp/cp-objcp-common.o cp/name-lookup.o cp/cxx-pretty-print.o cp/cp-gimplify.o tree-mudflap.o attribs.o c-common.o c-format.o c-pragma.o c-semantics.o c-lex.o c-dump.o  c-pretty-print.o c-opts.o c-pch.o c-incpath.o cppdefault.o c-ppoutput.o c-cppbuiltin.o prefix.o c-gimplify.o c-omp.o tree-inline.o dummy-checksum.o main.o  libbackend.a ../libcpp/libcpp.a ../libdecnumber/libdecnumber.a ../libcpp/libcpp.a   ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a -L/opt/local/lib -lmpfr -lgmp
ld: warning: could not create compact unwind for _set_compound_literal_name: dwarf uses DW_CFA_GNU_args_size
ld: warning: could not create compact unwind for _result_vector: dwarf uses DW_CFA_GNU_args_size
ld: warning: could not create compact unwind for _df_insn_rescan: dwarf uses DW_CFA_GNU_args_size
ld: warning: could not create compact unwind for _df_record_entry_block_defs: dwarf uses DW_CFA_GNU_args_size
ld: warning: could not create compact unwind for _df_record_exit_block_uses: dwarf uses DW_CFA_GNU_args_size
ld: warning: could not create compact unwind for _df_bb_refs_record: dwarf uses DW_CFA_GNU_args_size
ld: warning: could not create compact unwind for _compute_regsets: dwarf uses DW_CFA_GNU_args_size
duplicate symbol _init_inline_once in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _debug_find_tree in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _unsave_expr_now in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _insert_decl_map in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _copy_tree_r in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _clone_body in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _copy_body_r in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _estimate_move_cost in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _remap_decl in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _remap_type in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _build_duplicate_type in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _estimate_num_insns in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _flag_inline_trees in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _tree_inlinable_function_p in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _tree_versionable_function_p in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _tree_function_versioning in:
    tree-inline.o
    libbackend.a(tree-inline.o)
duplicate symbol _optimize_inline_calls in:
    tree-inline.o
    libbackend.a(tree-inline.o)
ld: 17 duplicate symbols for architecture x86_64
collect2: ld returned 1 exit status
make[7]: *** [cc1plus-dummy] Error 1
make[6]: *** [all-gcc] Error 2
make[5]: *** [all] Error 2
make[4]: [build] Error 2 (ignored)
```

**Comment by dfffffff** [comment]
Ok, this in an old issue for mac (https://trac.macports.org/ticket/20816).

**Comment by nils-eilers** [comment]
Yes, comment six says:

> Edit line 76 of the file and remove tree-inline.o from CXX_C_OBJS

That's what I did. The build works without tree-inline.o on Linux as well.

**Comment by dfffffff** [comment]
Merged, Thank You!

**Comment by nils-eilers** [comment]
Merci beaucoup!

BTW did you receive my e-mail about the installation scripts?

**Comment by dfffffff** [comment]
Yes, I'll give my feedback soon

**Comment by nils-eilers** [comment]
Just asking. There's no need to hurry, take your time.

**Pull request merged**
